# Generated by Django 4.2.3 on 2023-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agents",
            fields=[
                ("AgentID", models.AutoField(primary_key=True, serialize=False)),
                ("Queue", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("issueID", models.AutoField(primary_key=True, serialize=False)),
                ("userID", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("problem", models.TextField()),
                ("time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INQUEUE", "In Queue"),
                            ("ASSIGNED", "Assigned"),
                            ("DISPATCHED", "Dispatched"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
